### ISSUE TITLE
Possible to delete investigator? 

### ISSUE THREAD

**Issue by MatthewRichardsonICPSR** [ncrncornell/ced2ar#26]
For the repeatable fields like investigator, how does one delete an investigator? I didn't see an obvious option; emptying the investigator field still leaves an empty investigator in the edit screen.

**Comment by CSimmer** [comment]
This type of delete is not exposed in CED2AR today.

**Comment by CSimmer** [comment]
Fixed the delete issue on Principle Investigators (= stdyDscr/citation/rspStmt/AuthEnty).
There is now a trash can/delete icon to the right of the pencil/edit icon.

Also added delete icon to repeating fields:
Codebook prepared by (= docDscr/citation/prodStmt/producer)
Data prepared by (= stdyDscr/citation/prodStmt/producer)

Tested on Chrome and Safari.

jira: CDR-194
