### ISSUE TITLE
Ability to edit stdyDscr/citation/titlStmt if necessary

### ISSUE THREAD

**Issue by larsvilhuber** [ncrncornell/ced2ar#32]
The current interface only allows editing docDscr/citation/titlStmt (the "Codebook" title), but it may be necessary sometimes to edit the study-level title as well for something "prettier".
```
 <stdyDscr>
    <citation>
      <titlStmt>
        <titl>nyotda</titl>

```

**Comment by CSimmer** [comment]
Implemented in v2.9 under jira: [CDR-242](https://jira.cornell.edu/browse/CDR-242) Add study title (stdyDscr/citation/titlStmt/titl) to edit/codebooks page

github Commit Summary:
bdca489 - Added functionality to display and modify Study Title on edit/codebooks page.
