### ISSUE TITLE
Document legal values for OAUTH2 configuration

### ISSUE THREAD

**Issue by larsvilhuber** [ncrncornell/ced2ar#34]
From the Wiki page:

```
authenticationType=OAUTH2
supportedOauth2Providers=GOOGLE ORCID
authorizationStorage=PROPERTIES_FILE

#OAUTH2 Configuration
authCode=authorization_code
```
Describe the legal values that are accepted (or point to the source code.

Do a full working example for both Google and Orcid.

**Comment by bbarker** [comment]
:+1: good call. This is now fixed in the wiki
