### ISSUE TITLE
Uploads sometimes fail and produce bad error message: invalid XML

### ISSUE THREAD

**Issue by MatthewRichardsonICPSR** [ncrncornell/ced2ar#9]
I attempted to upload icpsr03496-0002.xml and got an error message about the XML being invalid. I validated the XML; there's nothing wrong with it. I then attempted the same file again. On the second pass, the upload worked with no errors. Interestingly enough, the second message said 

"Upload complete, icpsr03496-0002 (1) was sucessfully added. View codebook"

That (1) implies it received a second version of the same file...so it received the first file.

The only difference I noted between the two uploads was that I made the Label shorter on the second one, but I doubt that's the problem.

![screen shot 2017-02-17 at 3 57 09 pm 2](https://cloud.githubusercontent.com/assets/20051509/23083084/2d3ea19a-f52a-11e6-8596-e3105d0236c5.png)

**Comment by MatthewRichardsonICPSR** [comment]
When I attempted a larger file (~38MB), it failed the first three times, when I used the label "Desistance2000-2010". The fourth time, I tried just "Desistance" and it uploaded fine. 

And the next file I added had a hyphen in the label and caused no issues.

**Comment by Kbrums** [comment]
There is a 20 char limit on handle, label and version. The incorrect error message was being displayed but I have fixed that now.
